production:
  default_from_email: "noreply@azurie.com"
  default_to_email: "artem.kiselev@gmail.com"
development:
  default_from_email: "noreply@azurie.com"
  default_to_email: "artem.kiselev@gmail.com"
test:
  default_from_email: "noreply@azurie.com"
  default_to_email: "artem.kiselev@gmail.com"
