development:
  morphology: stem_en, stem_ru
  charset_type: utf-8
  charset_table: 0..9, A..Z->a..z, a..z, U+2D->0, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+0401->U+0435, U+0451->U+0435
  min_infix_len: 1
  enable_star: 1
production:
  morphology: stem_en, stem_ru
  charset_type: utf-8
  charset_table: 0..9, A..Z->a..z, a..z, U+2D->0, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+0401->U+0435, U+0451->U+0435
  min_infix_len: 1
  enable_star: 1
test:
  morphology: stem_en, stem_ru
  charset_type: utf-8
  charset_table: 0..9, A..Z->a..z, a..z, U+2D->0, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+0401->U+0435, U+0451->U+0435
  min_infix_len: 1
  enable_star: 1
