# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_resizing: true
theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,link,unlink,removeformat,image,code,|,styleselect,formatselect,fontselect,fontsizeselect"
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
# plugins:
#  - table
#  - fullscreen
