require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BriefingsController do

  # This should return the minimal set of attributes required to create a valid
  # Briefing. As you add validations to Briefing, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all briefings as @briefings" do
      briefing = Briefing.create! valid_attributes
      get :index
      assigns(:briefings).should eq([briefing])
    end
  end

  describe "GET show" do
    it "assigns the requested briefing as @briefing" do
      briefing = Briefing.create! valid_attributes
      get :show, :id => briefing.id.to_s
      assigns(:briefing).should eq(briefing)
    end
  end

  describe "GET new" do
    it "assigns a new briefing as @briefing" do
      get :new
      assigns(:briefing).should be_a_new(Briefing)
    end
  end

  describe "GET edit" do
    it "assigns the requested briefing as @briefing" do
      briefing = Briefing.create! valid_attributes
      get :edit, :id => briefing.id.to_s
      assigns(:briefing).should eq(briefing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Briefing" do
        expect {
          post :create, :briefing => valid_attributes
        }.to change(Briefing, :count).by(1)
      end

      it "assigns a newly created briefing as @briefing" do
        post :create, :briefing => valid_attributes
        assigns(:briefing).should be_a(Briefing)
        assigns(:briefing).should be_persisted
      end

      it "redirects to the created briefing" do
        post :create, :briefing => valid_attributes
        response.should redirect_to(Briefing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved briefing as @briefing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Briefing.any_instance.stub(:save).and_return(false)
        post :create, :briefing => {}
        assigns(:briefing).should be_a_new(Briefing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Briefing.any_instance.stub(:save).and_return(false)
        post :create, :briefing => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested briefing" do
        briefing = Briefing.create! valid_attributes
        # Assuming there are no other briefings in the database, this
        # specifies that the Briefing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Briefing.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => briefing.id, :briefing => {'these' => 'params'}
      end

      it "assigns the requested briefing as @briefing" do
        briefing = Briefing.create! valid_attributes
        put :update, :id => briefing.id, :briefing => valid_attributes
        assigns(:briefing).should eq(briefing)
      end

      it "redirects to the briefing" do
        briefing = Briefing.create! valid_attributes
        put :update, :id => briefing.id, :briefing => valid_attributes
        response.should redirect_to(briefing)
      end
    end

    describe "with invalid params" do
      it "assigns the briefing as @briefing" do
        briefing = Briefing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Briefing.any_instance.stub(:save).and_return(false)
        put :update, :id => briefing.id.to_s, :briefing => {}
        assigns(:briefing).should eq(briefing)
      end

      it "re-renders the 'edit' template" do
        briefing = Briefing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Briefing.any_instance.stub(:save).and_return(false)
        put :update, :id => briefing.id.to_s, :briefing => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested briefing" do
      briefing = Briefing.create! valid_attributes
      expect {
        delete :destroy, :id => briefing.id.to_s
      }.to change(Briefing, :count).by(-1)
    end

    it "redirects to the briefings list" do
      briefing = Briefing.create! valid_attributes
      delete :destroy, :id => briefing.id.to_s
      response.should redirect_to(briefings_url)
    end
  end

end
